### PR TITLE
Use multiple dispatch to swap on API route types

### PR DESCRIPTION
**Pull request by ghost**
The string literals used by this library made me feel radically uncomfortable. So I put some multiple dispatch on it.  

If I was you, I wouldn't take this merge, but it's a fun provocation. :smile_cat: Unit tests pass locally, but I'm not convinced they provide sufficient coverage so ymmv.

### CODE REVIEW

**Comment by rahulkp220** [comment]
@polytomous This is a great update and I really like it. 

However before I merge this, 
* could you also make changes to the `README.md` file so that the examples are in-line with the new fixes and we are good to go with the documentation as well.
* make sure to increase (or at least at the same level) the code-coverage.

**Review by rahulkp220 — APPROVED** [review]
I will merge it for now and update the `coverage` and `README.MD` later.

**Comment by ghost** [comment]
These uncovered lines: 
```hn_route_string(::Type{MaxItem}) = "maxitem"
hn_route_string(::Type{TopStories}) = "topstories"
hn_route_string(::Type{NewStories}) = "newstories"
hn_route_string(::Type{BestStories}) = "beststories"
hn_route_string(::Type{AskStories}) = "askstories"
hn_route_string(::Type{ShowStories}) = "showstories"
```

Encode an api that wasn't documented, the best way to add coverage would be to write unit tests that actually validated the documented behavior. (No, I am NOT adding a test like `@test hn_route_string(BestStories) == "beststories".) Seemed out of scope for this contribution, and tbh you can have fun with that i have other things to play with. 😸 

Can't wait to see what kind of cool code you write next~

**Comment by rahulkp220** [comment]
@polytomous have a try at this one next [Zabbix](https://github.com/rahulkp220/Zabbix.jl ), it's now a part of `METADATA.jl` and ready to be used.Thanks for your contribution, much appreciated.

**Pull request merged**
